# Generated by Django 5.1.6 on 2025-02-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField()),
            ],
        ),
    ]
