# Generated by Django 5.1.6 on 2025-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_menuitem_order_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(default='main_course', max_length=20),
        ),
    ]
